spring:
  application:
    name: authentication-service
  cloud:
    gateway:
      httpclient:
        max-header-size: 65536
    instance:
      hostname: ${spring.application.name}.${eureka.instance.instance-id}
      instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  data:
    mongodb:
      # uri: mongodb://localhost:27017/management_system?retryWrites=true&w=majority
      host: localhost
      port: 27017
      auto-index-creation: true
      database: management_system
      username: root
      password: hoangsang236
      authentication-database: admin

#eureka:
#  instance:
#    securePortEnabled: true
#    securePort: 8081
#    nonSecurePortEnabled: false
#    preferIpAddress: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: https://localhost:8761/eureka/
